/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_comp4905_jasonfleischer_midimusic_audio_NDKFunct */

#ifndef _Included_com_comp4905_jasonfleischer_midimusic_audio_NDKFunct
#define _Included_com_comp4905_jasonfleischer_midimusic_audio_NDKFunct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_comp4905_jasonfleischer_midimusic_audio_NDKFunct
 * Method:    writeSingleNoteFile
 * Signature: (IIIILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_comp4905_jasonfleischer_midimusic_audio_NDKFunct_writeSingleNoteFile
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring, jint);

/*
 * Class:     com_comp4905_jasonfleischer_midimusic_audio_NDKFunct
 * Method:    writeChordFile
 * Signature: (IIIILjava/lang/String;I[I)V
 */
JNIEXPORT void JNICALL Java_com_comp4905_jasonfleischer_midimusic_audio_NDKFunct_writeChordFile
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring, jint, jintArray);

/*
 * Class:     com_comp4905_jasonfleischer_midimusic_audio_NDKFunct
 * Method:    writeSequenceFile
 * Signature: (IIILjava/lang/String;I[I)V
 */
JNIEXPORT void JNICALL Java_com_comp4905_jasonfleischer_midimusic_audio_NDKFunct_writeSequenceFile
  (JNIEnv *, jclass, jint, jint, jint, jstring, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
